[tool.streamlit]
name = Crypto Trading Bot
description = Crypto Trading Bot with multiple coin support, backtesting, and mobile notifications
repository = https://github.com/GiannoUnchained/Crypto-Trading-Bot
python_version = 3.10

